// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5rFpl_cicnN_d__QRp8QZ-O6eO3nfld0',
    appId: '1:991757989925:web:59993ada3fc3be0524a7cc',
    messagingSenderId: '991757989925',
    projectId: 'cart-app-93ba5',
    authDomain: 'cart-app-93ba5.firebaseapp.com',
    storageBucket: 'cart-app-93ba5.appspot.com',
    measurementId: 'G-7P08843LPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqE1iNDvtoSBeXcub-MzyEHF7OP11vP8M',
    appId: '1:991757989925:android:f6fab5127de4536724a7cc',
    messagingSenderId: '991757989925',
    projectId: 'cart-app-93ba5',
    storageBucket: 'cart-app-93ba5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGJjYVkKZ4p3l1h4ZTY1UUkW9vNsF8sxI',
    appId: '1:991757989925:ios:7c939e035cac902c24a7cc',
    messagingSenderId: '991757989925',
    projectId: 'cart-app-93ba5',
    storageBucket: 'cart-app-93ba5.appspot.com',
    iosBundleId: 'com.example.cartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGJjYVkKZ4p3l1h4ZTY1UUkW9vNsF8sxI',
    appId: '1:991757989925:ios:e48ca35156557f2024a7cc',
    messagingSenderId: '991757989925',
    projectId: 'cart-app-93ba5',
    storageBucket: 'cart-app-93ba5.appspot.com',
    iosBundleId: 'com.example.cartApp.RunnerTests',
  );
}
